export interface IProfile {
    id: number,
    name: string,
    latitude: number,
    longitude: number,
    location: string,
    likes: [],
    age: number,
    birthday: number,
    monthofbirth: number,
    yearofbirth: number,
    gender: number,
    gendervapor: number,
    photomain: number,
    photolink: [],
    signzodiac: number,
    education: number,
    fieldofactivity: number,
    maritalstatus: number,
    children: number,
    religion: number,
    rise: number,
    smoke: number,
    alcohol: number,
    discription: string,
    profit: number,
    interests: [],
    ilikecharacter: [],
    idontlikecharacter: [],
    vapors: [],
    likepeople: [],
    dislikepeople: [], 
}

export interface IProfileShort {
    jwt: string,
    email: string,
    password: string,
}
