export interface IFilterUsers {
    location: string,
    agestart: number,
    ageend: number,
    growthstart: number,
    growthend: number,
    weightstart: number,
    weightend: number,
    signzodiac: number,
    gendervapor: number,
    religion: number,
    smoke: number,
    alcohol: number,
    interests: [],
}

export interface IProfile {
    id: number,
    name: string,
    latitude: number,
    longitude: number,
    location: string,
    likes: [],
    age: number,
    birthday: number,
    monthofbirth: number,
    yearofbirth: number,
    growth: number,
    weight:number,
    gender: number,
    gendervapor: number,
    photomain: number,
    photolink: [],
    signzodiac: number,
    education: number,
    fieldofactivity: number,
    maritalstatus: number,
    children: number,
    religion: number,
    rise: number,
    smoke: number,
    alcohol: number,
    discription: string,
    profit: number,
    interests: [],
    ilikecharacter: [],
    idontlikecharacter: [],
    filters: IFilterUsers,
}

export interface IProfileShort {
    id: number,
    name: string,
    age: number,
    photomain: number,
    photolink: [],
    interests: [],
}
